const corePlatformData={currentPlatform:'youtube',activeTier:'micro',exchangeRate:83.5,geoMultipliers:{Global:1,India:.55,US:1.6,UK:1.4,Canada:1.35,Australia:1.3,UAE:1.2,Pakistan:.4,Bangladesh:.35},nicheFactors:{technology:1.3,finance:1.5,education:1.2,business:1.25,gaming:.9,entertainment:1,lifestyle:.95,beauty:1.05,fitness:1,travel:.95},tierSponsorshipBase:{nano:120,micro:450,mega:1800},youtube:{adRpmLow:2,adRpmHigh:6,shortRpmLow:.03,shortRpmHigh:.12,color:'#ff3355'},tiktok:{adRpmLow:.2,adRpmHigh:1.2,shortRpmLow:.2,shortRpmHigh:1.2,color:'#9d4edd'},facebook:{adRpmLow:.3,adRpmHigh:.8,shortRpmLow:.05,shortRpmHigh:.25,color:'#1d9bf0'}};

window.addEventListener('DOMContentLoaded',()=>{initTheme();switchPlatform('youtube',document.querySelector('.tab-btn.youtube'));checkCookieConsent();});

function initTheme(){const saved=localStorage.getItem('omni_theme')||'dark';document.body.setAttribute('data-mode',saved);updateThemeButton();}
function toggleTheme(){const current=document.body.getAttribute('data-mode')||'dark';const next=current==='dark'?'light':'dark';document.body.setAttribute('data-mode',next);localStorage.setItem('omni_theme',next);updateThemeButton();}
function updateThemeButton(){const btn=document.getElementById('theme-toggle');if(!btn)return;const mode=document.body.getAttribute('data-mode')||'dark';btn.textContent=mode==='dark'?'☀️ Light':'🌙 Dark';}

function switchPlatform(platformName,button){corePlatformData.currentPlatform=platformName;document.body.setAttribute('data-theme',platformName);const activeColor=corePlatformData[platformName].color;document.documentElement.style.setProperty('--accent',activeColor);document.documentElement.style.setProperty('--accentGlow',activeColor+'47');document.querySelectorAll('.tab-btn').forEach(btn=>btn.classList.remove('active'));if(button)button.classList.add('active');updateCalculations();}
function applyPreset(tier,button){corePlatformData.activeTier=tier;document.querySelectorAll('.preset-badge').forEach(b=>b.classList.remove('active'));if(button)button.classList.add('active');const viewSlider=document.getElementById('slider-views');const shortsSlider=document.getElementById('slider-shorts');const dealsSlider=document.getElementById('slider-deals');if(tier==='nano'){viewSlider.value=85000;shortsSlider.value=950000;dealsSlider.value=1}else if(tier==='micro'){viewSlider.value=2500000;shortsSlider.value=75000000;dealsSlider.value=8}else{viewSlider.value=42000000;shortsSlider.value=410000000;dealsSlider.value=22}updateCalculations();}
function getInputs(){return{views:parseFloat(document.getElementById('slider-views').value)||0,shorts:parseFloat(document.getElementById('slider-shorts').value)||0,deals:parseFloat(document.getElementById('slider-deals').value)||0,currency:document.getElementById('currency-select').value,geo:document.getElementById('country-select').value,niche:document.getElementById('niche-select').value};}
function formatCompact(num){if(num>=1e9)return(num/1e9).toFixed(1)+'B';if(num>=1e6)return(num/1e6).toFixed(1)+'M';if(num>=1e3)return(num/1e3).toFixed(0)+'K';return Math.round(num).toString();}
function formatMoney(num,currency){const symbol=currency==='INR'?'₹':'$';const factor=currency==='INR'?corePlatformData.exchangeRate:1;const locale=currency==='INR'?'en-IN':'en-US';return symbol+Math.round(num*factor).toLocaleString(locale);}
function calculateSegments(inputs){const cfg=corePlatformData[corePlatformData.currentPlatform];const geo=corePlatformData.geoMultipliers[inputs.geo]||1;const niche=corePlatformData.nicheFactors[inputs.niche]||1;const sponsorBase=corePlatformData.tierSponsorshipBase[corePlatformData.activeTier]||450;const adLow=(inputs.views/1000)*cfg.adRpmLow*geo*niche;const adHigh=(inputs.views/1000)*cfg.adRpmHigh*geo*niche;const shortsLow=(inputs.shorts/1000)*cfg.shortRpmLow*geo*niche;const shortsHigh=(inputs.shorts/1000)*cfg.shortRpmHigh*geo*niche;const brandLow=inputs.deals*sponsorBase*geo*niche*.75;const brandHigh=inputs.deals*sponsorBase*geo*niche*1.45;const affiliateLow=(adLow+shortsLow)*.05;const affiliateHigh=(adHigh+shortsHigh)*.18;return{adLow,adHigh,shortsLow,shortsHigh,brandLow,brandHigh,affiliateLow,affiliateHigh};}
function updateCalculations(){const inputs=getInputs();document.getElementById('views-display').innerText=inputs.views.toLocaleString('en-US');document.getElementById('shorts-display').innerText=inputs.shorts.toLocaleString('en-US');document.getElementById('deals-display').innerText=`${inputs.deals} / month`;const s=calculateSegments(inputs);const adMid=(s.adLow+s.adHigh)/2;const shortsMid=(s.shortsLow+s.shortsHigh)/2;const brandMid=(s.brandLow+s.brandHigh)/2;const affiliateMid=(s.affiliateLow+s.affiliateHigh)/2;const totalLow=s.adLow+s.shortsLow+s.brandLow+s.affiliateLow;const totalHigh=s.adHigh+s.shortsHigh+s.brandHigh+s.affiliateHigh;const totalMid=adMid+shortsMid+brandMid+affiliateMid;document.getElementById('total-range').innerText=`${formatMoney(totalLow,inputs.currency)} - ${formatMoney(totalHigh,inputs.currency)} / mo`;document.getElementById('alt-total-range').innerText=inputs.currency==='USD'?`≈ ${formatMoney(totalLow,'INR')} - ${formatMoney(totalHigh,'INR')}`:`≈ ${formatMoney(totalLow,'USD')} - ${formatMoney(totalHigh,'USD')}`;document.getElementById('breakdown-ad').innerText=formatMoney(adMid,inputs.currency);document.getElementById('breakdown-shorts').innerText=formatMoney(shortsMid,inputs.currency);document.getElementById('breakdown-brand').innerText=formatMoney(brandMid,inputs.currency);document.getElementById('breakdown-affiliate').innerText=formatMoney(affiliateMid,inputs.currency);document.getElementById('final-sum').innerText=formatMoney(totalMid,inputs.currency);document.getElementById('range-ad').innerText=`${formatMoney(s.adLow,inputs.currency)} - ${formatMoney(s.adHigh,inputs.currency)}`;document.getElementById('range-shorts').innerText=`${formatMoney(s.shortsLow,inputs.currency)} - ${formatMoney(s.shortsHigh,inputs.currency)}`;document.getElementById('range-brand').innerText=`${formatMoney(s.brandLow,inputs.currency)} - ${formatMoney(s.brandHigh,inputs.currency)}`;document.getElementById('range-affiliate').innerText=`${formatMoney(s.affiliateLow,inputs.currency)} - ${formatMoney(s.affiliateHigh,inputs.currency)}`;document.getElementById('final-range').innerText=`${formatMoney(totalLow,inputs.currency)} - ${formatMoney(totalHigh,inputs.currency)}`;document.getElementById('goal-symbol').innerText=inputs.currency==='USD'?'$':'₹';calculateReverseGoal();}
function calculateReverseGoal(){const inputs=getInputs();const targetInput=parseFloat(document.getElementById('target-amount').value)||0;const targetUsd=inputs.currency==='USD'?targetInput:targetInput/corePlatformData.exchangeRate;const geo=corePlatformData.geoMultipliers[inputs.geo]||1;const niche=corePlatformData.nicheFactors[inputs.niche]||1;function requiredViews(platformName,type){const cfg=corePlatformData[platformName];const low=cfg[type+'Low'];const high=cfg[type+'High'];const rpm=((low+high)/2)*geo*niche;if(!rpm||rpm<=0)return'0';return formatCompact((targetUsd/rpm)*1000)}document.getElementById('target-yt-views').innerText=requiredViews('youtube','adRpm');document.getElementById('target-tt-views').innerText=requiredViews('tiktok','shortRpm');document.getElementById('target-fb-views').innerText=requiredViews('facebook','adRpm');}
function toggleFaq(element){const isOpen=element.classList.contains('open');document.querySelectorAll('.faq-item').forEach(item=>item.classList.remove('open'));if(!isOpen)element.classList.add('open');}
const complianceDocs={about:`<h2>About OmniCreator Planner</h2><p>OmniCreator Planner is an educational creator earnings estimation tool. It helps creators, agencies and brands plan potential income using selected inputs, public benchmark ranges and transparent assumptions.</p><p>It is not an official calculator from YouTube, TikTok, Facebook or Meta.</p>`,privacy:`<h2>Privacy Policy</h2><p>For this demo, calculator inputs run in your browser. We do not require login or account creation for basic estimates.</p><p>We may use local storage to remember your theme preference and cookie notice choice. Do not enter private or sensitive personal information into the calculator.</p>`,terms:`<h2>Terms of Use</h2><p>OmniCreator Planner provides educational estimates only. The numbers shown are planning ranges and not guaranteed earnings.</p><p>Actual creator income may vary due to platform policy, monetization status, audience country, watch time, engagement, advertiser demand and brand negotiations.</p>`,disclaimer:`<h2>Disclaimer</h2><p>Estimates are based on public benchmarks and selected inputs. Actual earnings may vary.</p><p>OmniCreator Planner is not affiliated with YouTube, TikTok, Facebook or Meta. All trademarks belong to their respective owners.</p>`,methodology:`<h2>How Calculation Works</h2><p>The calculator uses platform RPM ranges, country multiplier, niche multiplier, sponsorship assumptions and affiliate assumptions. It creates an educational range, not a guaranteed payout.</p>`,contact:`<h2>Contact</h2><p>For support, corrections or business inquiries, contact support@omnicreatorplanner.com.</p>`};
function openModal(type){document.getElementById('modal-content').innerHTML=complianceDocs[type]||complianceDocs.disclaimer;document.getElementById('modal-overlay').style.display='flex';}
function closeModal(){document.getElementById('modal-overlay').style.display='none';}
function acceptCookies(){localStorage.setItem('omni_cookie_notice_v2','accepted');document.getElementById('cookie-bar').style.display='none';}
function openCookiePanel(){document.getElementById('cookie-bar').style.display='flex';}
function checkCookieConsent(){const bar=document.getElementById('cookie-bar');if(!bar)return;if(localStorage.getItem('omni_cookie_notice_v2')==='accepted'){bar.style.display='none'}else{bar.style.display='flex'}}